- name: Install the EPEL release package
  ansible.builtin.dnf:
    name: epel-release
    state: present
  when: ansible_distribution == "Rocky" and ansible_distribution_major_version == "9"
  become: true

- name: Ensure the EPEL repository is enabled
  ansible.builtin.yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux
    baseurl: https://download.fedoraproject.org/pub/epel/9/Everything/x86_64/
    enabled: true
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9
  when: ansible_distribution == "Rocky" and ansible_distribution_major_version == "9"
  become: true

- name: Install core packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ core_packages }}"
  become: true

- name: Create user account
  ansible.builtin.user:
    name: "patrick"
    password: "{{ users.patrick.password }}"
    shell: "{{ users.patrick.shell }}"
    groups: "{{ users.patrick.groups }}"
    create_home: true
    state: present
  become: true

- name: "Ensure .ssh directory exists for user"
  ansible.builtin.file:
    path: "/home/patrick/.ssh"
    state: directory
    owner: patrick
    group: patrick
    mode: "0700"
  become: true

- name: "Setup ssh public key for user"
  ansible.builtin.lineinfile:
    line: "{{ users.patrick.pubkey }}"
    path: "/home/patrick/.ssh/authorized_keys"
    create: true
    owner: patrick
    group: patrick
    mode: "0600"
  become: true

- name: Allow wheel group to use sudo with nopasswd
  community.general.sudoers:
    name: "wheel-allow-nopasswd"
    group: wheel
    commands: ALL
    nopassword: true
    state: present
  become: true
