- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: Restart pihole service
  ansible.builtin.service:
    name: pihole
    state: restarted
  become: true
