- name: Enable docker repository
  ansible.builtin.yum_repository:
    name: docker-ce
    description: "Docker CE Stable - $basearch"
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
    gpgkey: "https://download.docker.com/linux/centos/gpg"
    gpgcheck: true
    enabled: true
  become: true

- name: Install docker packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_packages }}"
  become: true

- name: Enable and start docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
